### ISSUE TITLE
Multi-file upload hangs after first file.

### ISSUE THREAD

**Issue by wrex** [cadriel/fluidd#255] opened 2021-04-20 16:11 UTC
## Affected Version(s):
- klipper version: v0.9.1-436
- moonraker version: v0.5.0-20
- fluidd version: v1.12.2

## Platform:
MacOS 11.2.3
Chrome Version 89.0.4389.128 (Official Build) (x86_64)

## Hardware Configuration:
iMac
(Voron v0.0 but unlikely to be related)

## Reproduction Steps:
1. Select "Upload" from vertical dots menu in Jobs widget on Dashboard
2. Select three gcode files from system browser
3. Wait

## Actual Results:
First file uploads. Next ones hang as shown in attached screenshot.

Must refresh browser to regain control, then see error message "Metadata not available for <4x2-compartments - 0.2-0.4 41.3824g - 2h46m.gcode>" (or whatever filename).

## Screenshot(s):
<img width="1385" alt="Screen Shot 2021-04-20 at 9 02 13 AM" src="https://user-images.githubusercontent.com/653208/115429316-257dfc00-a1b8-11eb-8f24-6a12f8b6fa7e.png">

## Expected Results:
Three files expected to upload consecutively.

## Log Files:
- klipper log: 
[klippy (2).log](https://github.com/cadriel/fluidd/files/6345034/klippy.2.log)

- moonraker log: 
[moonraker (1).log](https://github.com/cadriel/fluidd/files/6345037/moonraker.1.log)

## Additional information
As always, thanks for the fantastic software and responsive support!

**Comment by StuSerious** [comment] 2021-04-20 19:23
Hey there @wrex, thanks for taking the time to submit a detailed bug report!

This looks to me like a dupe of #239 (see comments there)
A temporary fix is to drag and drop the files instead of selecting them

A fix is slated for the next release!
Have a nice day :D

**Closed** 2021-04-20 20:58 UTC
Labels: bug
